### ISSUE TITLE
reload ammo widget should be a bit smarter?

### ISSUE THREAD

**Issue by kanatohodets** [spring1944/spring1944#110]
hoko and I both keep it disabled -- it interferes with my orders, and orders stuff back to base when I have a halftrack or truck coming soon.

does anyone use it? is it a good thing on the whole?

**Comment by Lowdive** [comment]
Definitely interferes with my orders, sometimes my combined arms operations
get thwarted because tanks or guns go back to base for some R&R (and
reloading).
I think ammo indicators are good enough, you can react to the visual cue
and do something, but so far, them acting on their own has not given me any
edge on battle.

On Mon, Jun 15, 2015 at 2:43 PM, Ben Tyler <notifications@github.com> wrote:

> hoko and I both keep it disabled -- it interferes with my orders, and
> orders stuff back to base when I have a halftrack or truck coming soon.
>
> does anyone use it? is it a good thing on the whole?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spring1944/spring1944/issues/110>.
>



-- 
José Elí Santiago Rodríguez.
Disponibilidad de Horario.
<https://www.google.com/calendar/embed?src=elisantiago.4e%40gmail.com&ctz=America/Mexico_City&mode=Week>

**Comment by yuritch** [comment]
I have it disabled, but only because it still sometimes causes units exiting factory to return to it immediately (and block it in the process)

**Comment by ashdnazg** [comment]
Ok, it seems no one has it on currently, I'm going to disable it for now
