### ISSUE TITLE
Vehicles dominating battlefield early game

### ISSUE THREAD

**Issue by buumi** [spring1944/spring1944#193]
Especially all autocannon vehicles are problematic at the moment. They can basically drive into enemy infantry, kill all the inf and leave without any inf support as long as they don't stop to shoot (which they do not need to). They're even too fast for most AT infantry as well as AT guns. This leads to situation where almost every map only viable strategy is to go vehicle yard first and build infantry only once LoS is needed.

**Comment by yuritch** [comment]
I've implemented vehicle immobilization to help with this.

Basically some weapons (currently grenades and AT rifles) have a change to immobilize a vehicle for 10 seconds, which should allow the defenders some time to deal with it. Might be interesting to add this to autocannons as well, so that deployed AA guns can do it.

Chance is about 19% per hit for grenades and 38% for most anti-tank rifles vs light armored vehicles. It is higher vs unarmored trucks and lower vs tanks.

**Comment by buumi** [comment]
Sounds very nice

**Comment by jal76** [comment]
now you got it, vehicle tactics dont work anymore, so most will jump to tanks, they dont die that fast vs grenades

**Comment by buumi** [comment]
They still work with scouting or as quick supports. 

Anyways, I agree with jal on this one with a few test games. It feels wrong currently (e.g Scott stopping to move for 10 seconds just because of grenade). I don't have improvement ideas yet though. Personally i liked the old grenades the most in inf vs vehicle combat but i know jal disagrees on this and agree that from realism point of view it was weird :)

**Comment by yuritch** [comment]
Ok, I'll remove immobilization from HE grenades, and add it to light AT guns.

This will be a straight buff for light vehicles because light AT usually 1-2 shots them anyway, but it's meant to still deter tanks a bit.

How does that sound?

**Comment by sanguinariojoe** [comment]
This was done so long ago... I'm closing the issue
