### ISSUE TITLE
notAChili license missing

### ISSUE THREAD

**Issue by sanguinariojoe** [spring1944/spring1944#288]
Since just a subfolder of chiliui has been copied to the notAChili submodule, the GPL license statement is missing.

**Comment by PepeAmpere** [comment]
@sanguinariojoe 

* I cannot commit to repo directly for some reason
* I cannot create the mirror hook as well because owner rights are needed for this. Even if I would have the rights, making the mirror hook is not zero time effort. 

Module was updated in https://bitbucket.org/notabots/notachili/commits/a918a2af64ab11db2d6494f53549d9eb0d59bf06

but without linking the bitbucket repo directly I have no way how to continue with this.

**Comment by sanguinariojoe** [comment]
Easy peasy! Even without the hook (and you can do that by yourself)

```
git clone https://github.com/spring1944/submodule-notAchili.git
git remote add upstream https://bitbucket.org/notabots/notachili.git
git fetch upstream
git merge upstream/master
git push origin master
```

https://github.com/spring1944/submodule-notAchili/commit/a918a2af64ab11db2d6494f53549d9eb0d59bf06
