### ISSUE TITLE
string "LuaRules/Gadgets/flag_placer.lua"]:68: attempt to perform arithmetic on field '?' (a string value)

### ISSUE THREAD

**Issue by abma** [spring1944/spring1944#291]
[f=-000001] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=Initialize trace=[Internal Lua error: Call failure] error = 2, LuaGadgets/gadgets.lua, [string "LuaRules/Gadgets/flag_placer.lua"]:68: attempt to perform arithmetic on field '?' (a string value)
stack traceback:
	[C]: in function 'Include'
	[string "LuaRules/main.lua"]:1: in main chunk

https://buildbot.springrts.com/builders/validationtests/builds/5694/steps/validation%20test_6/logs/stdio

**Comment by PepeAmpere** [comment]
Hah, great @abma, btw I see some other worms in the more detailed log (than I usually have) you posted.

**Comment by sanguinariojoe** [comment]
That's because it's not spring1944...

`[f=-000001] [PreGame::AddGameSetupArchivesToVFS] using game: Imperial Winter test-100-c4fdc08 (archive: a9a5a6aba08b76534ce1738776d1577d.sdp)`

I close the issue @abma 

(Anyway, if you wanna fix Imperial Winter contact with me, I made a lot of changes some time ago)

**Comment by abma** [comment]
ugh, sorry!

it was definitly to late :-|

**Comment by sanguinariojoe** [comment]
no problem man!
