### ISSUE TITLE
S44 UI options shall be moved

### ISSUE THREAD

**Issue by sanguinariojoe** [spring1944/spring1944#296]
The file `modules/notAchili/ss44UI/config/epicmenu_conf.lua` (and probably all others inside `modules/notAchili/ss44UI/config`) shall be moved sopmewhere out of submodules. Otherwise options cannot be conveniently added/modified.

**Comment by PepeAmpere** [comment]
check the submodules structure @sanguinariojoe, you maybe missed the design

i created submodules structure with exactly this in mind

* `<moduleName>/data` - this is the folder where subrepo is stored, all the "shared" files which are "hard to change"
* `<moduleName> rest around` is free space for any type of configuration, good habit is to place the things in `<moduleName>/config` or `<moduleName>/<configFamilyName>/config` as you can see it for ss44UI

so i guess the issue is not valid

**Comment by sanguinariojoe** [comment]
You are completely right! Thanks!
