### ISSUE TITLE
Display info on units that are loaded into trucks/halftracks/boats in the UI

### ISSUE THREAD

**Issue by Firedow** [spring1944/spring1944#398]
Hey joe, i noticed that units loaded into transports are not displayed in the selection bar

Making these units icons transparent or adding the icon of the transport they're in on the corner plus having them chained to the transport is the way to go (in my nota UI experience again)

**Comment by sanguinariojoe** [comment]
Uhm... Too much information, isn't it?

**Comment by Firedow** [comment]
Oh not at all, knowing what units are inside a vehicle/boat is such a important feedback (to me so far), i had a match where i sended an empty truck into the frontline and left my full one in my spawn for example, the only way so far to know is to zoom-in or unload and see if the command cancels itself

For me having the information excludes the need to zoom-in and it lets me know exactly what units are still inside

**Comment by sanguinariojoe** [comment]
Uhm... I can think a way to have that info (as less intrusive as possible)

**Comment by sanguinariojoe** [comment]
OK, I made some changes so now the units loaded in the selected transports are shown as icons:

![image](https://user-images.githubusercontent.com/1668392/96259766-5b9ab300-0fbe-11eb-851f-d99285bbae73.png)

It is however not serializing the transporters, i.e. they are still grouped by unit types. Thus, all the transporters of the same kind, with all the loaded units are stacked together.

I think it is a good balance. The logic of the widget is kept rather simple (and therefore robust and efficient enough) and a lot of information is made available in the GUI in a straightforward way, without becoming overwhelming. On the other hand, it is not possible to know which transporters are loaded and which are not.

Since it does not exactly implements the solution you suggested, I mark the issue as "more-data-required", waiting for your feedback.

**Comment by Firedow** [comment]
Oh that seems really nice, im just worried about (seeing from the image) for example a commissar being overshadowed by riflemans, but grouped icons of the same units looks great

I got the behaviour of selecting trucks individually just to see the unit icons, and that would tell me that truck was loaded, this ticks that box so it should be good ;))

**Comment by sanguinariojoe** [comment]
Then I mark it as resolved, to be closed after merging. (further issues can be open in the future just in case)
