### ISSUE TITLE
Deformable maps don't work

### ISSUE THREAD

**Issue by Leo512bit** [spring1944/spring1944#466]
I tried many maps (including deformable maps for other games and maps that are specifically made for sp44) but I couldn't get the terrain to deform at all.

**Comment by Lowdive** [comment]
just checking here but, did you disable the default option in the game? :
the lua file engine options has undeformable maps set to true as default
```
key    = "DisableMapDamage",
    name   = "Undeformable map",
    desc   = "Prevents the map shape from being changed by weapons (key = 'DisableMapDamage')",
    type   = "bool",
    def    = true,
```

**Comment by Leo512bit** [comment]
Yup I did that in the skirmish menu in the Spring Lobby.

**Comment by Lowdive** [comment]
Alright, sorry, I had to ask since it wasn't specified.
Now I have digged into it and it seems to be that the default weapon definition has cratermult set to 0, only very specific weapons have cratermult set to some value higher than 0 (those being apmines and atmines).
You can replicate crater goodiness by loading map arctic plains v2.1, with the underformable map option set to false, and then plant a bunch of apmines and or atmines, and blow them up, and you will get craters.

**Comment by Leo512bit** [comment]
Thanks! But just wondering why doesn't other weapons have a `cratermult `value thats greater than 0? And will other weapons get values in the future? (I never modded Spring so sorry if its a dumb question.)

**Comment by Lowdive** [comment]
I can't answer that with absolute knowledge, but I assume it's because cratering ends up making difficult terrain for vehicles. No cratering allows for a more standard gameplay experience for all players, as opposed to deformable maps where the experience for each game on the same map could change drastically, denying areas for vehicles, creating stuck vehicles, even stuck infantry, etc.
I don't think weapons will get cratermult updated (this is also just my opinion).
A main dev might be able to answer your question more accurately.

However as an issue I think this one should be closed since the game option works as intended.
@FLOZi

**Comment by Leo512bit** [comment]
> I can't answer that with absolute knowledge, but I assume it's because cratering ends up making difficult terrain for vehicles. No cratering allows for a more standard gameplay experience for all players, as opposed to deformable maps where the experience for each game on the same map could change drastically, denying areas for vehicles, creating stuck vehicles, even stuck infantry, etc.

Everything seemed to work fine although I should do more testing before I will say that with confidence. Also the engineers can restore the terrain to its original height not to mention deformable maps are disabled (and from my knowledge very few even support the option in the first place).

>I don't think weapons will get cratermult updated (this is also just my opinion).

Just wondering what files contain the `cratermult` for weapons? I still might want to play around with it for offline play.

**Comment by Lowdive** [comment]
https://github.com/spring1944/spring1944/commit/c103f71255a95447342165707042f0e4d26e7050
in the weapons folder I think you need to modify for each weapon, aditionally, in the commit I linked above, you can see there's some more weapons that can create craters. @Leo512bit

**Comment by FLOZi** [comment]
You can either modify for weapons individually, modify the base weapon classes in BaseClasses or even apply it unilaterally in gamedata/weapondefs_post.lua
