### ISSUE TITLE
fix up smoke CEG

### ISSUE THREAD

**Issue by kanatohodets** [spring1944/spring1944#79]
smoke CEG is killing our players with lower spec rigs. we can probably improve the situation a bit:

1) It is probably denser than it strictly needs to be; you should still be able to see unit icons inside it.
2) The large scale smoke rounds result in a very spherical/tall effect. If we flatten it out, we could probably drop some particles.

**Comment by Lowdive** [comment]
nice! thanks for thinking of us!

On Wed, Apr 1, 2015 at 10:59 AM, Ben Tyler <notifications@github.com> wrote:

> smoke CEG is killing our players with lower spec rigs. we can probably
> improve the situation a bit:
>
> 1) It is probably denser than it strictly needs to be; you should still be
> able to see unit icons inside it.
> 2) The large scale smoke rounds result in a very spherical/tall effect. If
> we flatten it out, we could probably drop some particles.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spring1944/spring1944/issues/79>.
>



-- 
José Elí Santiago Rodríguez.
Disponibilidad de Horario.
<https://www.google.com/calendar/embed?src=elisantiago.4e%40gmail.com&ctz=America/Mexico_City&mode=Week>

**Comment by kanatohodets** [comment]
I pushed some tweaks -- Lowdive, mind checking them out?

**Comment by Lowdive** [comment]
not at all! will test them out asap <--- stressing out the "as soon as
possible" part

On Wed, Apr 8, 2015 at 4:33 PM, Ben Tyler <notifications@github.com> wrote:

> I pushed some tweaks -- Lowdive, mind checking them out?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spring1944/spring1944/issues/79#issuecomment-91042684>
> .
>



-- 
José Elí Santiago Rodríguez.
Disponibilidad de Horario.
<https://www.google.com/calendar/embed?src=elisantiago.4e%40gmail.com&ctz=America/Mexico_City&mode=Week>

**Comment by Lowdive** [comment]
Haven't done a comparison between previous version smoke performance and
new version smoke performance but I had about 24 units smoking (different
smokesizes: mortar, sherman, light howitzer) an I had no visible
performance bogs (other than the usual lag spike I get from spring engine),
though I noticed smoke clouds that detonated or spawned way above ground,
dunno if that happens because of one of the tweaks...
neverthless I'll keep testing it out.

On Wed, Apr 8, 2015 at 4:36 PM, Elí Santiago <elisantiago.4e@gmail.com>
wrote:

> not at all! will test them out asap <--- stressing out the "as soon as
> possible" part
>
> On Wed, Apr 8, 2015 at 4:33 PM, Ben Tyler <notifications@github.com>
> wrote:
>
>> I pushed some tweaks -- Lowdive, mind checking them out?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/spring1944/spring1944/issues/79#issuecomment-91042684>
>> .
>>
>
>
>
> --
> José Elí Santiago Rodríguez.
> Disponibilidad de Horario.
> <https://www.google.com/calendar/embed?src=elisantiago.4e%40gmail.com&ctz=America/Mexico_City&mode=Week>
>



-- 
José Elí Santiago Rodríguez.
Disponibilidad de Horario.
<https://www.google.com/calendar/embed?src=elisantiago.4e%40gmail.com&ctz=America/Mexico_City&mode=Week>

**Comment by kanatohodets** [comment]
feedback at the moment is: looks mostly ok, but clipping through the ground looks really terrible. will close this and open a new issue to discuss converting smoke to LUPS, which can handle that more nicely
